name: mt
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - pip=19.3
  - pytorch=1.3
  - torchvision=0.4
  - ignite=0.2
  - tensorboard=2.0
  - numpy=1.17
  - pandas=0.25
  - scikit-learn=0.21
  - tqdm=4.38
  - jupyter=1.0
  - jupyterlab=1.2
  - seaborn=0.9
  - bokeh=1.4
  - pytest=5.2
  - pyarrow=0.15
  - jupyter=1.0
  - pip:
      - scikit-video~=1.1
      - dacite~=1.1