name: mt
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - pip=19.3
  - pytorch==1.3.1
  #  - cudatoolkit==10.1
  - torchvision==0.4.2
  - ignite==0.2.1
  - pillow==6.2
  - numpy==1.17.5
  - pandas==0.25.3
  - pyarrow==0.15.1
  - scikit-learn==0.22.1
  - tqdm==4.41.1
  - seaborn==0.9.0
  - pytest==5.3.4
  - jupyter==1.0.0
  - jupyterlab==1.2.5
  - opencv==4.2.0
  - pip:
      - scikit-video==1.1.11
      - imgaug==0.3.0
      - dacite==1.2.0
      - patool==1.12
