name: mt
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - pip=19.3
  - numpy=1.17
  - pandas=0.25
  - pyarrow=0.15
  - scikit-learn=0.21
  - pytorch=1.3
  - torchvision=0.4
  - ignite=0.2
  - tensorboard=2.0
  - tqdm=4.38
  - seaborn=0.9
  - pytest=5.2
  - jupyter=1.0
  - jupyterlab=1.2
  - pip:
      - scikit-video~=1.1
      - opencv-python~=4.1
      - imgaug~=0.3
      - dacite~=1.1
      - patool~=1.12