name: mt
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pip
  - pytorch=1.1.0
  - torchvision
  - ignite
  - pandas
  - opencv
  - scikit-learn
  - scikit-image
  - scikit-video
  - tqdm
  - matplotlib
  - bokeh
  - jupyter
  - requests
  - seaborn
  - tensorboardx
  - pip:
      - autopep8
      - tensorboard
      - git+https://github.com/pytorch/ignite.git
