name: mt
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.6
  - tensorflow
  - tensorflow-probability
  - pytorch
  - torchvision
  - ignite
  - pandas
  - opencv
  - scikit-learn
  - scikit-image
  - scikit-video
  - tqdm
  - matplotlib
  - bokeh
  - jupyter
  - pip:
      - dataclasses
      - memory-profiler
      - dm-sonnet
      - autopep8
